GET
  FILE='E:\Users\Alex\Google Drive\Haiti\HaitiT1T2data2.8 in progress.sav'.
DATASET NAME DataSet1 WINDOW=FRONT.
GET
  FILE='E:\Users\Alex\Google Drive\Haiti\Haiti_Time3_zeros.sav'.
DATASET NAME DataSet2 WINDOW=FRONT.
DATASET ACTIVATE DataSet1.
SORT CASES BY T1ParticipantID(A) T2PartID(A).
DATASET ACTIVATE DataSet2.
SORT CASES BY T1ParticipantID(A) Q4b(A).
DATASET ACTIVATE DataSet2.
DATASET CLOSE DataSet1.
DATASET ACTIVATE DataSet2.

DATASET ACTIVATE DataSet1.
STAR JOIN
  /SELECT t1.Time1, t1.T1ResponseID, t1.hasT1T2data, t1.trainingparticipant, t1.intvscontrol, 
    t1.randomization, t1.T1DataRef, t1.T1, t1.T1IPAddress, t1.T1Status, t1.T1StartDate, t1.T1EndDate, 
    t1.T1Finished, t1.T1Listrapèl, t1.T2PartID, t1.T1ResearcherName, t1.T1Date, t1.Locationcode, 
    t1.T1Location, t1.Finalgender, t1.T1Gender1F2M, t1.T2.gender, t1.VAR00012, t1.T1Age, t1.T2.age, 
    t1.VAR00011, t1.T1T2match, t1.T1Married, t1.T2Mar, t1.T1Numberofchildren, t1.T2Numofchildren, 
    t1.T1DISASTERPREPAREDNESSMEASURE , t1.T11.Madeadisastersupplykit, 
    t1.T11B.Haveyouthoughtabouthowtousetheitemsyouhaveinyourhousealread, 
    t1.T12.Keptanextrasupplyofimportantmedicationinasafeplace, 
    t1.T13.Storedextrawaterorfoodintheeventofadisaster, 
    t1.T14.Putimportantdocumentsinasafeplacee.g.inaplasticbag, 
    t1.T15.Secureddwellingfromwindandrainormadestrongerinsomeotherway, 
    t1.T16.Raisedfurnitureorotheritemsoffthefloorinanticipationoffloodi, 
    t1.T17.Dugacanalcleanedravinesorusedsandbagstodivertwaterandminimiz, 
    t1.T18.Removedobjectsfromyourhomeoryardthatcanblowaroundandhurtsome, 
    t1.T19.Discussedafamilyemergencyplan, 
    t1.T110.Discussedanevacuationplanwheretogoifyouneedtoleavethecamp, 
    t1.T111.Discussedaplanforreconnectingwithfamilyifseparated, 
    t1.T112.Talkedtochildrenaboutwhattodointheeventofadisaster, 
    t1.T113.ListenedtotheradiowatchedTVlookedatcomputertocheckforadvers, 
    t1.T114.Learnedaboutfirstaide.g.howtostopbleedingwhattodoifsomeoneb, 
    t1.T115.Learnedhowtoaccesscleanwaterafteradisaster, 
    t1.T116. Learnedhowtodisinfectpossessionsafterexposuretofloodwater, 
    t1.T117.Learnedhowtomaintainsanitationintheaftermathofadisaster, 
    t1.T118.Learnedaboutthesafestplacetostaywhetherinone’shomeoroutsi, 
    t1.T119.Learnedwhattodoifburiedaliveinanearthquake, 
    t1.T120.Learnedthesafestplacetogoifwatersbegintorise, 
    t1.T121.Mappedriskyandsafeplacesandusefulresourcesinyourcommunityin, 
    t1.T122.Consideredhowyoumighthelpneighborsandfriendsintheeventofadi, 
    t1.T123.Whatelseifanythinghaveyoudonetoprepareforadisaster, 
    t1.T124.AreyouawareofwheretofindconsultcommunityrepresentativesorNG, 
    t1.T125.Haveyoueverattendedadisasterpreparednesstrainingprovidedbyt, 
    t1.T125B.Pleaseindicateorganizationsponsoringthetraining, 
    t1.T126.Othercommentsfortheresearchteamaboutpreparingfordisasters, t1.T1PERCEIVEDRISKSELFEFFICACY, 
    t1.T11.Howableareyoutotakethetimetoprepareforadisaster17, 
    t1.T12.Canyouaffordtobuytheitemsneededtoprepareforadisaster17, 
    t1.T13.Howmuchknowledgedoyouhaveabouthowtoprepareforadisaster17, 
    t1.T1DISASTERRELATEDMENTALHEALTHCONCERNS, 
    t1.T11.Howanxiousornervousdoesitmakeyoufeeltothinkaboutfuturedisast, 
    t1.T12. Howhopelessordepresseddoesitmakeyoufeeltothinkaboutfutured, 
    t1.T13.Howmuchdoyoutrytoavoidthinkingaboutfuturedisasters17, t1.T1DISASTERSPECIFICFATALISMSD1SA5, 
    t1.T11.Idon’tworryaboutdisastersbecauseitisinGod’shands, 
    t1.T12.IfIaminjuredinadisasterGodintendedthattohappen, t1.T1SOURCECREDIBILITY, 
    t1.T11A.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11B.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11C.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11D.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11E.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11F.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11G.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T11H.Howmuchconfidencedoyouhavethatthesesourceswillbehelpfulinth, 
    t1.T12.Whowouldyoutrustthemosttobehelpfulintheeventofadisaster, t1.T1DISASTERATTRIBUTIONscale14, 
    t1.T11A.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11B.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11C.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11D.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11E.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11F.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, 
    t1.T11G.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe20, t1.T11GTEXT, 
    t1.T12A.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, 
    t1.T12B.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, 
    t1.T12C.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, 
    t1.T12D.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, 
    t1.T12E.FaultoftheHaitianpeoplee.g.moraltransgression, 
    t1.T12F.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, 
    t1.T12G.Howmuchdoyoubelievethatthefollowingfactorscausedvariousfloo, t1.T12GText, 
    t1.T13A.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13B.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13C.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13D.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13E.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13F.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, 
    t1.T13G.Whydoyouthinkthatparticularpeoplewereinjuredorkilledinthese, t1.T13GText, 
    t1.T1CHRONICSTRESSORS1.InthelastyearhaveyouHadaproblemwithfoodthatc, 
    t1.T1CHRONICSTRESSORS2.Inthelastyearhaveyouhadaproblemwithwaterthat, 
    t1.T1CHRONICSTRESSORS3.InthelastyearhaveyouHadaproblemwithshelterth, 
    t1.T1CHRONICSTRESSORS5.InthelastyearhaveyouHadaproblemwithbeinghara, 
    t1.T1CHRONICSTRESSORS6.InthelastyearhaveyouHadaproblemwithbeinghara, 
    t1.T1CHRONICSTRESSORS7.InthelastyearhaveyouHadaproblemwithaccesstoh, 
    t1.T1CHRONICSTRESSORS8.InthelastyearhaveyouHadaproblemwithaccesstos, 
    t1.T1CHRONICSTRESSORS9.InthelastyearhaveyouHadaproblemwithworkemplo, 
    t1.T1CHRONICSTRESSORS10.InthelastyearhaveyouHadaproblemwithaccessto, 
    t1.T1CHRONICSTRESSORS11.InthelastyearhaveyouHadaproblemfeelinghumil, 
    t1.T1CHRONICSTRESSORS12.InthelastyearhaveyouIsthereaprobleminyourpr, 
    t1.T1CHRONICSTRESSORS4.InthelastyearhaveyouHadaproblemwithsafetytha, 
    t1.T1TRAUMAEXPOSUREPleaseindicatewhetheryouhaveexperiencedwitnessed, t1.T11.Earthquake, 
    t1.T11B.Ifyeshowmanytimes, t1.T12.Hurricane, t1.T12B.Ifyeshowmanytimes, t1.T13.Flood, 
    t1.T13B.Ifyeshowmanytimes, t1.T14.Choleraorotherdiseaseepidemic, t1.T14B.Ifyeshowmanytimes, 
    t1.T15.Fireexplosion, t1.T15B.Ifyeshowmanytimes, 
    t1.T16.Housebadlydamagedordestroyedasaresultofadisaster, t1.T16B.Ifyeshowmanytimes, 
    t1.T17.Hadtomoveasaresultofadisastere.g.intoacamp, t1.T17B.Ifyeshowmanytimes, 
    t1.T18.Injuryinadisaster, t1.T18B.Ifyeshowmanytimes, t1.T19. Trappedunderrubbleinadisaster, 
    t1.T19B.Ifyeshowmanytimes, t1.T110. Closefriendsorfamilyinjuredbyadisaster, 
    t1.T110B.Ifyeshowmanytimes, t1.T111.Closefriendsorfamilykilledbyadisaster, 
    t1.T111B.Ifyeshowmanytimes, t1.T112.Transportationaccident, t1.T112B.Ifyeshowmanytimes, 
    t1.T113.Otherseriousaccident, t1.T113B.Ifyeshowmanytimes, t1.T114.Physicalassault, 
    t1.T114B.Ifyeshowmanytimes, t1.T115.Unwantedoruncomfortablesexualexperienceincludingsexualassau, 
    t1.T115B.Ifyeshowmanytimes, t1.T116.Combatorexposuretopoliticalviolenceorcivilconflict, 
    t1.T116B.Ifyeshowmanytimes, t1.T117.Captivitykidnappedorheldagainstyourwill, 
    t1.T117B.Ifyeshowmanytimes, t1.T118.Lifethreateningillness, t1.T118B.Ifyeshowmanytimes, 
    t1.T119.Suddenviolentdeathofsomeoneclosetoyou, t1.T119B.Ifyeshowmanytimes, 
    t1.T120.Suddenviolentdeathofsomeoneelsee.g.astrangerinatrafficaccid, t1.T120B.Ifyeshowmanytimes, 
    t1.T121.Seriousinjuryharmordeathyoucausedtosomeoneelse, t1.T121B.Ifyeshowmanytimes, t1.T1PTSDMPSS, 
    t1.T11.Duringthepast2weekshaveyoueverstruggledwithaseriesofthoughts, 
    t1.T11B.Atwhatpointwasitserious, 
    t1.T12.Doyouhavenightmaresanddreamsthatkeepyouterrifiedaboutwhatsha, 
    t1.T12B.Atwhatpointwasitserious, 
    t1.T13.Doyouhavetheimpressionthatyousuddenlyrelivewhathashappenedth, 
    t1.T11C.Atwhatpointwasitserious, 
    t1.T14.Isthisusuallywhenyourememberwhathappenedliketheendofthething, 
    t1.T14B.Atwhatpointwasitserious, 
    t1.T15.Doyoumakeanefforttonotassociatethoughtsandfeelingswithwhatsh, 
    t1.T15B.Atwhatpointwasitserious, 
    t1.T16.Doyouintendtoavoidactivitiessituationsorplacesthatremindyouo, 
    t1.T16B.Atwhatpointwasitserious, 
    t1.T17.Aretheresomekeythingsthatyouforgetaboutwhathappenedevenifyou, 
    t1.T17B.Atwhatpointwasitserious, 
    t1.T18.Isthereanythingthatdoesnotinterestyouanymoresincethetimeitha, 
    t1.T18B.Atwhatpointwasitserious, t1.T19.Doyoufeelisolatedordetachedfrompeoplesincethetimeithappened,
     t1.T19B.Atwhatpointwasitserious, 
    t1.T110.Doyouthinkthatyouarenotsensitiveinthesamewaysinceithadhappe, 
    t1.T110B.Atwhatpointwasitserious, 
    t1.T111.Haveanyplansorhopeschangedbecauseofwhathashappenedincluding, 
    t1.T111B.Atwhatpointwasitserious, 
    t1.T112.Doyouhaveproblemssleepingduringthenightsincethetimeithappen, 
    t1.T112B.Atwhatpointwasitserious, t1.T113.Doyoufeelupsetmoreeasilysincethetimeithadhappened, 
    t1.T113B.Atwhatpointwasitserious, t1.T114.Dofeelitishardertofocussinceithappened, 
    t1.T114B.Atwhatpointwasitserious, t1.T115.Doyoususpectmanylikewatchingthatpersonhavepassedsincethen,
     t1.T115B.Atwhatpointwasitserious, t1.T116.Areyousurprisedmoreeasilysincethenhavepassed, 
    t1.T116B.Atwhatpointwasitserious, 
    t1.T117.Doyoufeelbodyreactionslikesweatingandincreasedheartbeatswhe, 
    t1.T117B.Atwhatpointwasitserious, t1.T118.Howlonghasthisbeenbotheringyou, 
    t1.T1DEPRESSIONZLSI1.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI2.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI3.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI4.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI5.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI6.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI7.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI8.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI9.Duringthepast15dayshowmanytimeshasoneofthesepr, 
    t1.T1DEPRESSIONZLSI10.Duringthepast15dayshowmanytimeshasoneofthesep, 
    t1.T1DEPRESSIONZLSI11.Duringthepast15dayshowmanytimeshasoneofthesep, 
    t1.T1DEPRESSIONZLSI12.Duringthepast15dayshowmanytimeshasoneofthesep, 
    t1.T1DEPRESSIONZLSI13.Duringthepast15dayshowmanytimeshasoneofthesep, 
    t1.T1ANXIETY1.DuringthepasttwoweekshowmanytimesdidthisbotheryouCann, 
    t1.T1ANXIETY2.DuringthepasttwoweekshowmanytimesdidthisbotheryouYouf, 
    t1.T1ANXIETY3.DuringthepasttwoweekshowmanytimesdidthisbotheryouFeel, 
    t1.T1ANXIETY4.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoyo, 
    t1.T1ANXIETY5.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoyo, 
    t1.T1ANXIETY6.DuringthepasttwoweekshowmanytimesdidthisbotheryouDizz, 
    t1.T1ANXIETY7.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoes, 
    t1.T1ANXIETY8.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoyo, 
    t1.T1ANXIETY9.DuringthepasttwoweekshowmanytimesdidthisbotheryouArey, 
    t1.T1ANXIETY10.DuringthepasttwoweekshowmanytimesdidthisbotheryouDid, 
    t1.T1ANXIETY11.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY12.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY13.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY14.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY15.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY16.Duringthepasttwoweekshowmanytimesdidthisbotheryouanv, 
    t1.T1ANXIETY17.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY18.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY19.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1ANXIETY20.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoe, 
    t1.T1ANXIETY21.DuringthepasttwoweekshowmanytimesdidthisbotheryouDoy, 
    t1.T1LOCALIDIOMSOFDISTRESS1.Howmanytimeshaveyoufeltorexperiencedint, 
    t1.T1LOCALIDIOMSOFDISTRESS2.Howmanytimeshaveyoufeltorexperiencedint, 
    t1.T1LOCALIDIOMSOFDISTRESS3.Howmanytimeshaveyoufeltorexperiencedint, 
    t1.T1LOCALIDIOMSOFDISTRESS4.Howmanytimeshaveyoufeltorexperiencedint, t1.T14.Text, 
    t1.T1Isthepersonamanorawoman, t1.T1FUNCTIONASSESSMENTMen1.HowdifficultisJobs, 
    t1.T1FUNCTIONASSESSMENTMen2.HowdifficultisSupportingyourfamily, 
    t1.T1FUNCTIONASSESSMENTMen3.HowdifficultisCommunitysupport, 
    t1.T1FUNCTIONASSESSMENTMen4.HowdifficultisPlantingtreesforreforesta, 
    t1.T1FUNCTIONASSESSMENTMen5.Forallthereasonsyousaywhatarethereasons, t1.T15.TEXT, 
    t1.T1FUNCTIONASSESSMENTWomen1.HowdifficultisWork, 
    t1.T1FUNCTIONASSESSMENTWomen2.HowdifficultisCleaning, 
    t1.T1FUNCTIONASSESSMENTWomen3.HowdifficultisTakingcareofyourchildre, 
    t1.T1FUNCTIONASSESSMENTWomen4.HowdifficultisCleaningthecommunity, 
    t1.T1FUNCTIONASSESSMENTWomen5.HowdifficultisParticipatingincommunit, 
    t1.T1FUNCTIONASSESSMENTWomen6.Foralltheresponsesyougavewhatthereaso, t1.T16Text, 
    t1.T1COPING1.WhathaveyoudonetofeelbettergoodinthelastweekJokelaugho, 
    t1.T1COPING2.WhathaveyoudonetofeelbettergoodinthelastweekDiscusspro, 
    t1.T1COPING3.WhathaveyoudonetofeelbettergoodinthelastweekHelporshar, 
    t1.T1COPING4.WhathaveyoudonetofeelbettergoodinthelastweekPrayreadth, 
    t1.T1COPING5.TellmyselfthatGodwillprovide, 
    t1.T1COPING6.WhathaveyoudonetofeelbettergoodinthelastweekSingdanceo, 
    t1.T1COPING7.WhathaveyoudonetofeelbettergoodinthelastweekDrinkalcoh, 
    t1.T1COPING8.WhathaveyoudonetofeelbettergoodinthelastweekRelaxation, 
    t1.T1COPING9.WhathaveyoudonetofeelbettergoodinthelastweekParticipat, 
    t1.T1COPING10.WhathaveyoudonetofeelbettergoodinthelastweekTellmysel, 
    t1.T1COPING11.WhathaveyoudonetofeelbettergoodinthelastweekThinkabou, 
    t1.T1COPING12.WhathaveyoudonetofeelbettergoodinthelastweekUsedrugs, 
    t1.T1COPING13.WhathaveyoudonetofeelbettergoodinthelastweekTalktoavo, 
    t1.T1COPING14.WhathaveyoudonetofeelbettergoodinthelastweekWorkandor, 
    t1.T1COPING15.WhathaveyoudonetofeelbettergoodinthelastweekTrytoacce, 
    t1.T1COPING16.WhathaveyoudonetofeelbettergoodinthelastweekVisitadoc, 
    t1.T1COPING17.WhathaveyoudonetofeelbettergoodinthelastweekTakesteps, t1.T1SOCIALCOHESIONTRUST, 
    t1.T11.HowmuchdoyouagreewiththefollowingstatementsPeopleinthiscommu, 
    t1.T12.HowmuchdoyouagreewiththefollowingstatementsThisisacloseknitc, 
    t1.T13.HowmuchdoyouagreewiththefollowingstatementsPeopleinthiscommu, 
    t1.T14.HowmuchdoyouagreewiththefollowingstatementsPeopleinthiscommu, 
    t1.T15.HowmuchdoyouagreewiththefollowingstatementsPeopleinthiscommu, 
    t1.T1IfIwerethevictimofadisasterIcouldeasilyfindsomeonetohelpme, 
    t1.T1Iftheywouldhelphowmightothershelpyouintheeventofadisaster, t1.T1RELIGIOSITY, 
    t1.T11.HowoftendoyouvisitaVoudoudoctororattendapublicVoudouceremony, 
    t1.T12.HowoftendoyouspendtimeinprivateactivitiesassociatedwithVoudo, 
    t1.T13.Howoftendoyouattendchurchorotherreligiousmeetings, 
    t1.T14.Howoftendoyouspendtimeinprivatereligiousactivitiessuchaspray, 
    t1.T1HELPSEEKINGmentalhealthrelated, 
    t1.T11.Wouldyoubecomfortableseekinghelpfromothersifyouweresuffering, 
    t1.T12.Whatmightpreventyoufromseekinghelpfromothersifyouweresufferi, 
    t1.T13.1Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.2Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.3.Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffi, 
    t1.T13.4Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.5Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.6Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.7Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, 
    t1.T13.8Ifyouweresufferingfromsadnessorstressthatmadeyourlifediffic, t1.T13.8Text, 
    t1.T14.1Ofthoselistedabovewhichwouldyougotofirst, t1.T1FIRST, 
    t1.T14.2Ofthoselistedabovewhichwouldyougotosecond, t1.T1SECOND, 
    t1.T14.3Ofthoselistedabovewhichwouldyougotothird, t1.T1THIRD, 
    t1.T15.Pleasedescribewhatmostpeoplethinkaboutseekinghelpfromahospit, 
    t1.T16.Pleaseratewhetheryouthinksufferingfrommentaldistressisaperso, 
    t1.T17.Whatdoyouthinkistheprimarycauseofsadnessorstressmakinglifedi, t1.T1Q7Text, 
    t1.T18.Pleasedescribehowmostcommunitymembersviewotherssufferingfrom, 
    t1.T19.If3monthsafteramajordisasteryoufoundyourselfsadandcryingmuch, 
    t1.T110.Ifyoucouldntgetoutofbedformanydaysandwerefeelingdisorientat, 
    t1.T1HELPSEEKINGdisasterrelated, 
    t1.T11.Wouldyoubecomfortableseekinghelpfromothersifyouneededsomethi, 
    t1.T1Whatmightpreventyoufromseekinghelpfromothersifyouneededsomethi, 
    t1.T1HELPGIVINGmentalhealthrelated, 
    t1.T11.Ifyouencounteredsomeonewithmentalhealthproblemsinyourcommuni, 
    t1.T1Ifyeshowmightyouhelpthem , t1.T1Ifnowhatmightpreventyoufromhelpingthem, 
    t1.T12.Doyoufeelthatyouhavetheskillsnecessarytohelpsomeoneinyourcom, 
    t1.T13.Ifafewweeksafteramajordisasteryounoticedaneighborwassadandcr, 
    t1.T1Ifaneighborcouldnttgetoutofbedformanydaysandwasfeelingdisorien, 
    t1.T1HELPGIVINGdisasterrelated, t1.T11.Doyouthinkyouwouldbewillingtohelpothersinyourcommunitytoprep,
     t1.T1Ifyeswhattypeofsupportmightyoubewillingtogiveothersinyourcommu, 
    t1.T12.Doyouthinkyouwouldbewillingtohelpothersinyourcommunityinthea, 
    t1.T1Ifyeswhattypeofsupportmightyoubewillingtogiveothersinyourcom_A, 
    t1.T13.Inthepasthaveyouprovidedhelptoothersinyourcommunitytoprepare, 
    t1.T14.Inthepasthaveyouprovidedhelptoothersinyourcommunityintheafte, t1.T1DEMOGRAPHICS, 
    t1.T1Genderofparticipantm1F2, t1.T1Age_A, t1.T1Married_A, t1.T1Numberofchildren_A, 
    t1.T1Ifyouhavechildrenhowmanylivewithyou, t1.T1Ifyouhavechildrenhowmanyundertheageof10years, 
    t1.T1Whatwasyourtotalapproximateincomelastmonth, 
    t1.T1Pleaselistsourcesofyourincomeinthepastmonthwithapproximateamou, 
    t1.T1Howwelloffisyourfamilycomparedtoothersinthecommunity, 
    t1.T1Howlonghaveyoubeenlivinginthislocation, t1.T1HaveyoulivedinanIDPcamp, t1.T1Ifyeswhere, 
    t1.T1Forhowlong, t1.T1Areyouemployed, t1.T1Ifyeswhatisyourjob, t1.T1Areyouinschool, 
    t1.T1Howmanyyearsofeducationhaveyoucompleted, t1.T1Whatreligionsdoyoupractice, t1.T1FINI, 
    t1.T1LocationLatitude, t1.T1LocationLongitude, t1.T1LocationAccuracy, t1.Time2, 
    t1.ParticipantIDmatchT1T2, t1.T2ResponseID, t1.T2ResponseSet, t1.T2Name, 
    t1.T2ExternalDataReference, t1.T2EmailAddress, t1.T2IPAddress, t1.T2Status, t1.T2StartDate, 
    t1.T2EndDate, t1.T2Finished, t1.T2Name_A, t1.T2Date, t1.T2Location, t1.T2ParticipantID, 
    t1.T2Gender, t1.T2NA, t1.T2NA_A, t1.T2DISASTERPREPAREDNESSMEASURE, t1.T21.Madeadisastersupplykit, 
    t1.T21.b.Ifyesasktoseesupplykit.Doesparticipanthaveasupplykitavaila, t1.T2Contents, t1.T2Notes, 
    t1.T2Haveyouthoughtabouthowtousetheitemsyouhaveinyourhousealreadye, t1.T2Describe, 
    t1.T22.Keptanextrasupplyofimportantmedicationinasafeplace, 
    t1.T23.Storedextrawaterorfoodintheeventofadisaster, 
    t1.T23.b.Ifyesasktoseeextrasupplyofwaterandfood.Doesparticipanthave, 
    t1.T24.Putimportantdocumentsinasafeplacee.g.inaplasticbag, 
    t1.T24.b.Ifyesasktoseedocuments.Doesparticipanthavedocumentsinasafe, 
    t1.T25.Secureddwellingfromwindandrainormadestrongerinsomeotherwaye, 
    t1.T25.Secureddwellingfromwindandrainormadestrongerinsomeotherway_A, t1.T2Notes_A, 
    t1.T2Description, t1.T25.b.Ifyesasktoseewaysinwhichdwellinghasbeensecuredorstrengthen, 
    t1.T2Description_A, t1.T2Notes_B, 
    t1.T26.Raisedfurnitureorotheritemsoffthefloorinanticipationoffloodi, 
    t1.T26.b.Ifyesasktoseewaysthatitemshavebeenraisedoffthefloortoconfi, 
    t1.T27.Dugacanalcleanedravinesorusedsandbagstodivertwaterandminimiz, 
    t1.T27.Dugacanalcleanedravinesorusedsandbagstodivertwaterandminim_A, 
    t1.T27.NOTESNotesaboutcanalsorravinesltemgt, t1.T27.Description, 
    t1.T27.b.Ifyesasktoseewaysparticipanthastriedtodivertwater.Canparti, t1.T27.b.Description, 
    t1.T2Notes_C, t1.T28. Removedobjectsfromyourhomeoryardthatcanblowaroundandhurtso, 
    t1.T28. Description, t1.T29.Discussedafamilyemergencyplane.g.whowillcareforfamilymembers, 
    t1.T29.Descriptiom, t1.T210.Discussedanevacuationplanwheretogoifyouneedtoleavethecampe, 
    t1.T210.Description, t1.T211.Discussedaplanforreconnectingwithfamilyifseparated, 
    t1.T211.Description, t1.T212.Talkedtochildrenaboutwhattodointheeventofadisaster, 
    t1.T213.ListenedtotheradiowatchedTVlookedatcomputertocheckforadvers, 
    t1.T214.Learnedaboutfirstaide.g.howtostopbleedingwhattodoifsomeoneb, 
    t1.T215.Learnedhowtoaccesscleanwaterafteradisaster, 
    t1.T216. Learnedhowtodisinfectpossessionsafterexposuretofloodwater, 
    t1.T217.Learnedhowtomaintainsanitationintheaftermathofadisastere.g, 
    t1.T218.Learnedthesafestplacetogoifwatersbegintorise, t1.T218.Where, 
    t1.T219.Mappedriskyandsafeplacesandusefulresourcesinyourcommunityin, 
    t1.T219.b.Ifyespleasegiveoneexampleofariskyplaceandoneexampleofaris, t1.T219.b.Description, 
    t1.T219.b.Ifyespleasegiveoneexampleofariskyplaceandoneexampleofause, t1.T219.b.Description_A, 
    t1.T220.Consideredhowyoumighthelpneighborsandfriendsintheeventofadi, t1.T2Notes_D, 
    t1.T221.Whatelseifanythinghaveyoudonetoprepareforadisaster, 
    t1.T222.AreyouawareofwheretofindconsultcommunityrepresentativesorNG, 
    t1.T223.Othercommentsfortheresearchteamaboutpreparingfordisastersin, 
    t1.T2II.PERCEIVEDRISKSELFEFFICACY, t1.T21.Howableareyoutotakethetimetoprepareforadisaster, 
    t1.T22.Canyouaffordtobuytheitemsneededtoprepareforadisaster, 
    t1.T23.Howmuchknowledgedoyouhaveabouthowtoprepareforadisaster, 
    t1.T2III.HELPGIVINGdisasterrelatedrecentfloods, 
    t1.T21.Didyouprovidehelptoothersinyourcommunitytopreparefortherecen, t1.T21.Description, 
    t1.T22.Didyouprovidehelptoothersinyourcommunityintheaftermathofther, t1.T22.Description, 
    t1.T2IV.DISASTERRELATEDMENTALHEALTHCONCERNS, 
    t1.T21.Howanxiousornervousdoesitmakeyoufeeltothinkaboutfuturedisast, 
    t1.T22. Howhopelessordepresseddoesitmakeyoufeeltothinkaboutfutured, 
    t1.T23.Howmuchdoyoutrytoavoidthinkingaboutfuturedisasters, t1.T2V.DISASTERSPECIFICFATALISM, 
    t1.T21.Idon’tworryaboutdisastersbecauseitisinGod’shands, 
    t1.T22.IfIaminjuredinadisasterGodintendedthattohappen, t1.T2VI.DISASTERATTRIBUTION, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe201, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_A, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_B, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_C, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_D, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_E, 
    t1.T21.Howmuchdoyoubelievethateachofthefollowingfactorscausedthe2_F, t1.T21.Text, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrecen, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_A, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_B, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_C, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_D, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_E, 
    t1.T22.Howmuchdoyoubelievethatthefollowingfactorscausedthemostrec_F, t1.T22.Text, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamagean, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_A, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_B, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_C, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_D, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_E, 
    t1.T23.Whydoyouthinkthatparticularpeopleexperiencedpropertydamage_F, t1.T23.Text, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithfoodthatcausesyoustressmo, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithshelterthatcausesyoustres, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithbeingharassedbysecurityof, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithbeingharassedbyneighborst, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithaccesstohealthcareservice, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithaccesstosanitationfacilit, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemwithworkemploymentthatcausesy, 
    t1.T2VII.CHRONICSTRESSORSHadaproblemwithaccesstoeducationthatcauses, 
    t1.T2VII.CHRONICSTRESSORS Hadaproblemfeelinghumiliatedornotrespect, 
    t1.T2VII.CHRONICSTRESSORS Isthereaprobleminyourprivatelifethatcaus, 
    t1.T2VII.CHRONICSTRESSORSHadaproblemwithsafetythatcausesyoustressmo, 
    t1.T2VII.CHRONICSTRESSORSHadaproblemwithwaterfordrinkingorwashingth, t1.T2VIII.FLOODEXPOSURE, 
    t1.T21.Duringthefloodsdidyouliveinanareathatwasevacuated, t1.T22.Wasyourhomedamagedintheflood, 
    t1.T22.Description_A, t1.T23.Duringandinthedaysimmediatelyfollowingtheflooddidyouspendthe, 
    t1.T23.Description, t1.T24.Didyouhavetorelocatebecauseyourhousebecamestructurallyunsafe, 
    t1.T24.Description, t1.T25.Didyouneedorreceivefoodorwateraidaftertheflood, t1.T25.Description, 
    t1.T2Didyouneedorreceiveclothesaftertheflood, t1.T2Description_B, 
    t1.T27.Didyousufferfinancialdifficultiesbecauseoftheflood, 
    t1.T28.Didyoulosemovablegoodsinthefloode.g.furniture, t1.T28.Description, 
    t1.T28.b.Ifrelevantpleaseestimatefinanciallossescosttoreplace, 
    t1.T29.Wereyouphysicallyinjuredintheflood, t1.T29.Description, 
    t1.T210.Wereanymembersofyourfamilyoryourlovedonesphysicallyinjuredi, 
    t1.T211.Wasthereaperiodwhenyouwereuncertainaboutthewelfareoflovedon, t1.T211.Describe, 
    t1.T212.Wereyouinvolvedinrescueworksuchassupportingothercommunityme, t1.T212.Description, 
    t1.T2Notes_E, t1.T2IX.PTSDMPSS, t1.T21.Duringthepast2weekshaveyoueverstruggledwithaseriesofthoughts,
     t1.T21.b.Atwhatpointwasitserious, 
    t1.T22.Doyouhavenightmaresanddreamsthatkeepyouterrifiedaboutwhatsha, 
    t1.T22.b.Atwhatpointwasitserious, 
    t1.T23.Doyouhavetheimpressionthatyousuddenlyrelivewhathashappenedth, 
    t1.T23.b.Atwhatpointwasitserious, 
    t1.T24.Isthisusuallywhenyourememberwhathappenedliketheendofthething, 
    t1.T24.b.Atwhatpointwasitserious, 
    t1.T25.Doyoumakeanefforttonotassociatethoughtsandfeelingswithwhatsh, 
    t1.T25.b.Atwhatpointwasitserious, 
    t1.T26.Doyouintendtoavoidactivitiessituationsorplacesthatremindyouo, 
    t1.T26.b.Atwhatpointwasitserious, 
    t1.T27.Aretheresomekeythingsthatyouforgetaboutwhathappenedevenifyou, 
    t1.T27.b.Atwhatpointwasitserious, 
    t1.T28.Isthereanythingthatdoesnotinterestyouanymoresincethetimeitha, 
    t1.T28.b.Atwhatpointwasitserious, 
    t1.T29.Doyoufeelisolatedordetachedfrompeoplesincethetimeithappened, 
    t1.T29.b.Atwhatpointwasitserious, 
    t1.T210.Doyouthinkthatyouarenotsensitiveinthesamewaysinceithadhappe, 
    t1.T210.b.Atwhatpointwasitserious, 
    t1.T211.Haveanyplansorhopeschangedbecauseofwhathashappenedincluding, 
    t1.T211.b.Atwhatpointwasitserious, 
    t1.T212.Doyouhaveproblemssleepingduringthenightsincethetimeithappen, 
    t1.T212.b.Atwhatpointwasitserious, t1.T213.Doyoufeelupsetmoreeasilysincethetimeithadhappened, 
    t1.T213.b.Atwhatpointwasitserious, t1.T214.Dofeelitishardertofocussinceithappened, 
    t1.T214.b.Atwhatpointwasitserious, 
    t1.T215.Doyoususpectmanylikewatchingthatpersonhavepassedsincethen, 
    t1.T215.b.Atwhatpointwasitserious, t1.T216.Areyousurprisedmoreeasilysincethenhavepassed, 
    t1.T216.b.Atwhatpointwasitserious, 
    t1.T217.Doyoufeelbodyreactionslikesweatingandincreasedheartbeatswhe, 
    t1.T217.b.Atwhatpointwasitserious, t1.T218.Howlonghasthisbeenbotheringyou, t1.T2Notes_F, 
    t1.T2X.DEPRESSIONFeeldepressed, t1.T2X.DEPRESSIONYourheartfeelstight, 
    t1.T2X.DEPRESSIONThinkingtoomuch, t1.T2X.DEPRESSIONCryorfeellikecrying, 
    t1.T2X.DEPRESSIONFeellikenothingisinteresting, t1.T2X.DEPRESSIONdiscouragedwithlifelosinghope, 
    t1.T2X.DEPRESSIONDifficulttosleep, t1.T2X.DEPRESSIONFeelingtiredorhavenostrength, 
    t1.T2X.DEPRESSIONLostappetite, t1.T2X.DEPRESSIONFeellikelifegoeswrong, 
    t1.T2X.DEPRESSIONMoveortalkquietlyevenothersseethis, 
    t1.T2X.DEPRESSIONYoutellyourselfBetterdeadoryouhaveideastodobadthin, 
    t1.T2X.DEPRESSIONDifficultysleepingallnight, 
    t1.T2XI.anXIETYBeckanxietyInventoryCannotfeelyourhands, 
    t1.T2XI.anXIETYBeckanxietyInventoryYoufeelyourbodyiswarmanditamp#39, 
    t1.T2XI.anXIETYBeckanxietyInventoryFeelyourfeettrembling, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoufeelyoucannotrelax, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoufearsomethingworsemayhappen, 
    t1.T2XI.anXIETYBeckanxietyInventoryDizzyorlightheaded, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoesyourheartpound, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoustumble, t1.T2XI.anXIETYBeckanxietyInventoryAreyouafraid, 
    t1.T2XI.anXIETYBeckanxietyInventoryAreyounervousDidyoufeelpressured, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyouhaveafeelingofchoking, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyourhandstremble, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoufeelshaky, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoulosecontrolofyourself, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyouhavetroublebreathing, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyouhaveafearofdyingAreyouafrai, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyougetscaredDidyoufeelbullied, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyouhaveindigestionorbloating, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyoufeelfaint, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoesyourfacegetflush, 
    t1.T2XI.anXIETYBeckanxietyInventoryDoyousweatwithoutfeelinghot, 
    t1.T2XII.LOCALIDIOMSOFDISTRESSLossofcontrol, t1.T2XII.LOCALIDIOMSOFDISTRESSToomanythingsonone, 
    t1.T2XII.LOCALIDIOMSOFDISTRESSSadnesspity, t1.T2XII.LOCALIDIOMSOFDISTRESSComments, 
    t1.T2XII.CommentsTEXT, t1.T2Notes_G, t1.T2XIII.FUNCTIONASSESSMENTIsthepersonamanorawoman, 
    t1.T2FUNCTIONASSESSMENTJobs, t1.T2FUNCTIONASSESSMENTSupportingyourfamily, 
    t1.T2FUNCTIONASSESSMENTCommunitysupport, t1.T2FUNCTIONASSESSMENTPlantingtreesforreforestation, 
    t1.T2FUNCTIONASSESSMENTForallthereasonsyousaywhatarethegreatestreas, t1.T2FUNCTIONASSESSMENTText, 
    t1.T2FUNCTIONASSESSMENTWorktheland, t1.T2FUNCTIONASSESSMENTCleaning, 
    t1.T2FUNCTIONASSESSMENTTakingcareofyourfamily, t1.T2FUNCTIONASSESSMENTCleaningthecommunity, 
    t1.T2FUNCTIONASSESSMENTParticipatingincommunityevents, 
    t1.T2FUNCTIONASSESSMENTForallthereasonsyousaywhatarethegreatestre_A, t1.T2FUNCTIONASSESSMENTTEXT_A, 
    t1.T2XIV.COPINGJokelaughorplay, t1.T2XIV.COPINGDiscussproblemswithfriendsorfamily, 
    t1.T2XIV.COPINGHelporsharewithotherpeoplee.g.moneyfoodteachthings, 
    t1.T2XIV.COPINGPrayreadtheBibleattendchurch, t1.T2XIV.COPINGTellmyselfthatGodwillprovide, 
    t1.T2XIV.COPINGSingdanceorlistentomusic, t1.T2XIV.COPINGDrinkalcohol, 
    t1.T2XIV.COPINGRelaxationtechniquese.g.slowbreathing, 
    t1.T2XIV.COPINGParticipateinfestivalsritualsorholidays, 
    t1.T2XIV.COPINGTellmyselfthatmyreactionsarenormal, t1.T2XIV.COPINGThinkaboutandplanforthefuture, 
    t1.T2XIV.COPINGUsedrugs, t1.T2XIV.COPINGTalktoavoodoodoctororothertraditionalhealer, 
    t1.T2XIV.COPINGWorkandorkeepmyselfbusy, t1.T2XIV.COPINGTrytoacceptthethingsthatIcannotchange, 
    t1.T2XIV.COPINGVisitadoctorormentalhealthworker, t1.T2XIV.COPINGTakestepstoimprovemysituation, 
    t1.T2XV.SOCIALCOHESIONTRUST, t1.T21.Peopleinthiscommunityarewillingtohelptheirneighbors, 
    t1.T21.Thisisacloseknitcommunity, t1.T21.Peopleinthiscommunitycanbetrusted, 
    t1.T21.Peopleinthiscommunitygenerallydontgetalongwitheachother, 
    t1.T21.Peopleinthiscommunitydonotsharethesamevalues, 
    t1.T22.IfIwerethevictimofadisasterIcouldeasilyfindsomeonetohelpme, 
    t1.T23.Didyoureceivehelpfromothersduringtherecentfloods, t1.T23.Description_A, 
    t1.T2XVI.RELIGIOSITY, t1.T21.HowoftendoyouvisitaVoudoudoctororattendapublicVoudouceremony, 
    t1.T22.HowoftendoyouspendtimeinprivateactivitiesassociatedwithVoudo, 
    t1.T23.Howoftendoyouattendchurchorotherreligiousmeetings, 
    t1.T24.Howoftendoyouspendtimeinprivatereligiousactivitiessuchaspray, 
    t1.T24.b.Didanyofyourreligiousactivitieschangeasaresultoftherecentf, t1.T24.b.Description, 
    t1.T2XVII.HELPSEEKINGmentalhealthrelated, 
    t1.T21.Didyouexperienceorareyoucurrentlyexperiencingsadnessorstress, 
    t1.T21.b.Ifnocouldyousaysomethingaboutwhynot, 
    t1.T21.c.Ifyesdidyouseekhelpforthise.g.fromfriendsfamilymentalhealt, t1.T21.d.God, 
    t1.T21.d.Churchpastororpriest, t1.T21.d.Voudoupriest, t1.T21.d.Neighborscommunitymembers, 
    t1.T21.d.FamilyFriends, t1.T2thing, t1.T21.d.Communitybasedmentalhealthcareprovider, 
    t1.T21.d.Other, t1.T21.d.TEXT, t1.T22.Ifinthefutureyoubegantosufferfromsadnessorstressthatmadeyour, 
    t1.T23.Whatmightpreventyoufromseekinghelpfromothersifyouweresufferi, t1.T22.d.God, 
    t1.T22.d.Churchpastororpriest, t1.T22.d.Voudoupriest, t1.T22.d.Neighborscommunitymembers, 
    t1.T22.d.FamilyFriends, t1.T22.d.Hospitalorclinic, t1.T22.d.Communitybasedmentalhealthcareprovider, 
    t1.T22.d.Other, t1.T22.d.TEXT, t1.T25.Pleasedescribewhatmostpeoplethinkaboutseekinghelpfromahospit, 
    t1.T26.Pleaseratewhetheryouthinksufferingfrommentaldistressisaperso, 
    t1.T27.Whatdoyouthinkistheprimarycauseofsadnessorstressmakinglifedi, t1.T27.TEXT, 
    t1.T28.Pleasedescribehowmostcommunitymembersviewotherssufferingfrom, 
    t1.T29.If3monthsafteramajordisasteryoufoundyourselfsadandcryingmuch, 
    t1.T210.Ifyoucouldntgetoutofbedformanydaysandwerefeelingdisorientat, 
    t1.T2XVIII.HELPSEEKINGdisasterrelated, 
    t1.T21.Didyouseekhelpfromothersifyouneededsomethingtoprepareforthem, 
    t1.T21.b.Whatkindofhelpdidyouseek, t1.T2ney, t1.T21.b.Who, t1.T21.b.TEXT, 
    t1.T21.c.Ifnowhatpreventedyoufromseekinghelpfromothersifyouneededso, 
    t1.T22.Inthefuturewouldyoubecomfortableseekinghelpfromothersifyoune, 
    t1.T2XIX.HELPGIVINGmentalhealthrelated, 
    t1.T21.Ifyouencounteredsomeonewithmentalhealthproblemsinyourcommuni, 
    t1.T21.b.Ifyeshowmightyouhelpthem, t1.T21.c.Ifnowhatmightpreventyoufromhelpingthem, 
    t1.T22.Doyoufeelthatyouhavetheskillsnecessarytohelpsomeoneinyourcom, 
    t1.T23.Ifafewweeksafteramajordisasteryounoticedaneighborwassadandcr, 
    t1.T24.Ifaneighborcouldntgetoutofbedformanydaysandwasfeelingdisorie, 
    t1.T25.Didyouhelpsomeonewithmentalhealthissuesafterthemostrecentflo, t1.T25.TEXT, 
    t1.T26.Haveyoueverhelpedsomeonewithmentalhealthissues, t1.T26.TEXT, 
    t1.T2XX.HELPGIVINGdisasterrelated, t1.T2o, 
    t1.T21.b.Ifyeswhattypeofsupportmightyoubewillingtogiveothersinyourc, 
    t1.T22.Doyouthinkyouwouldbewillingtohelpothersinyourcommunityinthea, 
    t1.T22.b.Ifyeswhattypeofsupportmightyoubewillingtogiveothersinyourc, 
    t1.T23.Haveyoueverattendedadisasterpreparednesstrainingprovidedbyth, 
    t1.T23.b.Ifyespleaseindicatetheorganizationsponsoringthetraining, 
    t1.T2XXI.DEMOGRAPHICSEnfomasyonDetaye, t1.T21.Gender, t1.T22.Age, t1.T23.Married, 
    t1.T24.Howmanychildrendoyouhave104Other, t1.T24.Howmanychildrendoyouhave, 
    t1.T24.b.Howmanylivewithyou, t1.T24.c.Howmanyunder10years, t1.T25.Areyouemployed, 
    t1.T25.b.Ifyeswhatisyourjob, t1.T26.WhatwasyourtotalapproximateincomelastmonthHaitiandollars, 
    t1.T27.Pleaselistsourcesofyourincomeinthepastmonthwithapproximateam, 
    t1.T28.Howwelloffisyourfamilycomparedtoothersinthecommunity, 
    t1.T29.Howlonghaveyoubeenlivinginthislocation, t1.T210.HaveyoulivedinanIDPcamp, t1.T210.b.Where, 
    t1.T210.b.Howlong, t1.T211.Areyouinschool, t1.T212.Howmanyyearsofeducationhaveyoucompleted, 
    t1.T213.Whatreligionsdoyoupractice, t1.T2Notes_H, t1.T2IMPORTanTTRAININGSECTION, 
    t1.T21.DidyouparticipateinSLMsdisasterpreparednessmentalhealthtrain, 
    t1.T2Ifyoudidnotattendthetrainingwhynot, t1.T2Text, t1.T214.b.Ifyeshowmanysessionsdaysdidyouattend, 
    t1.T2Didyoureceiveagiftafterthetraining, t1.T2Text_A, 
    t1.T2DidyoufindthegiftusefulinanywayrelatedtodisastersPleaseexplain, 
    t1.T214.c.WhichAjandidyouworkwith, 
    t1.T214.d.Pleaseratethistrainingona15scale.Helpingyoutocopewithdist, 
    t1.T214.d.Pleaseratethistrainingona15scale.Improvingtrustandrelatio, 
    t1.T214.d.Pleaseratethistrainingona15scale.Usefulness, 
    t1.T214.d.Pleaseratethistrainingona15scale.Helpingyoutoprepareforre, 
    t1.T214.e.Howmightthistrainingbeimprovedinthefuture, t1.T2Notes_I, 
    t1.T2FiniBontravay FinishedGoodjob, t1.T2FINIBontravayRanplifòmdebriefjwennpatisypankontak Envit, 
    t1.T2LocationLatitude, t1.T2LocationLongitude, t1.T2LocationAccuracy, t1.disasterselfeffsumT1, 
    t1.disasterselfeffsumT2, t1.disasteranxsumT1, t1.disasterMHsumT1, t1.disasterMHsumT2, 
    t1.depressionsumT1, t1.depressionsumT2, t1.anxsumT1, t1.anxsumT2, t1.disasterfatsumT1, 
    t1.disasterfatsumT2, t1.socialcohT1, t1.socialcohT2, t1.PTSDsumT2, t1.PTSDsumT1, t1.coping7RCT1, 
    t1.coping12RCT1, t1.coping7RCT2, t1.coping12RCT2, t1.disasterprepsumT1, t1.disasterprepsumT2, 
    t1.controlgroup, t1.disasterprepsumNo24121819T1, t1.disasterprepsumNo2412T2, t1.religT1, 
    t1.disasterattribT1, t1.disasterattribT2, t1.copingsumT1, t1.copingsumT2, t1.chronstressT2, 
    t1.chronstressT1, t1.helpgivingdisastT1, t1.helpgivingdisterT2, t1.helpgivingmentalT1, 
    t1.helpgivingmentalT2, t1.helpseekdisastT1, t1.helpseekdisasterT2, t1.helpseekmentalT1, 
    t1.helpseekmentalT2, t1.filter_$, t1.traumahist, t1.sourcecred, t1.functmenavgT1, 
    t1.functwomenavgT1, t1.functmenavgT2, t1.functwomenavgT2, t1.funcavgT1, t1.functavgT2, t0.V8, 
    t0.V9, t0.V10, t0.Instruc, t0.Q1, t0.Q2, t0.Q3, t0.Q4b, t0.Q5, t0.IDinstruc, t0.Instruc.0, 
    t0.Instruc.1, t0.Q1.0, t0.Q2.0, t0.Q2_TEXT, t0.notes, t0.Q3.0, t0.Q3_TEXT, t0.Q4.0, t0.Q5.0, t0.Q6, 
    t0.Q7, t0.Q8, t0.Q9_1, t0.Q9_2, t0.Q9_4, t0.Q9_4_TEXT, t0.Q10, t0.Q10_TEXT, t0.notes.0, t0.Q11, 
    t0.Q12, t0.Q13_1, t0.Q13_2, t0.Q13_4, t0.Q13_4_TEXT, t0.Q14, t0.Q14_TEXT, t0.notes.1, t0.Q15, 
    t0.Q15_TEXT, t0.Q16, t0.Q16_TEXT, t0.Q17, t0.Q17_TEXT, t0.Q18, t0.Q18_TEXT, t0.Q19, t0.Q20, t0.Q21, 
    t0.Q22, t0.Q23, t0.Q24, t0.Q25, t0.Q26, t0.Q27, t0.Q27_TEXT, t0.Q28, t0.Q29_1, t0.Q29_1_TEXT, 
    t0.Q29_2, t0.Q29_2_TEXT, t0.Q30, t0.notes.2, t0.Q31, t0.Q32, t0.Q33, t0.Q34, t0.Q34_TEXT, t0.Q35, 
    t0.notes.3, t0.Heading, t0.Q36, t0.Q37, t0.Q38, t0.Heading.0, t0.Q39, t0.Q40, t0.Q41, t0.Q42, 
    t0.Q43, t0.Q44, t0.Q45, t0.Q46_1, t0.Q46_2, t0.Q46_3, t0.Q46_4, t0.Q46_5, t0.Q46_6, t0.Q46_7, 
    t0.Q46_7_TEXT, t0.Q47_1, t0.Q47_2, t0.Q47_3, t0.Q47_4, t0.Q47_5, t0.Q47_6, t0.Q47_7, t0.Q47_7_TEXT, 
    t0.Q48_1, t0.Q48_2, t0.Q48_3, t0.Q48_4, t0.Q48_5, t0.Q48_6, t0.Q48_7, t0.Q48_7_TEXT, t0.Q49_1, 
    t0.Q49_3, t0.Q49_5, t0.Q49_6, t0.Q49_7, t0.Q49_8, t0.Q49_9, t0.Q49_10, t0.Q49_11, t0.Q49_12, 
    t0.Q49_13, t0.Q49_22, t0.Q50, t0.Q51, t0.Q52, t0.Q53, t0.Q54, t0.Q55, t0.Q56, t0.Q57, t0.Q58, 
    t0.Q59, t0.Q60, t0.Q61, t0.Q62, t0.Q63, t0.Q64, t0.Q65, t0.Q66, t0.Q67, t0.Q68, t0.Q69, t0.Q70, 
    t0.Q71, t0.Q72, t0.Q73, t0.Q74, t0.Q75, t0.Q76, t0.Q77, t0.Q78, t0.Q79, t0.Q80, t0.Q81, t0.Q82, 
    t0.Q83, t0.Q84, t0.Q85, t0.Q86, t0.Q87, t0.Q88, t0.Q89, t0.Q90, t0.Q91, t0.Q92, t0.Q93, t0.Q94, 
    t0.Q95, t0.Q96, t0.Q97, t0.Q98, t0.Q99, t0.Q100, t0.Q101, t0.Q102, t0.Q103, t0.Q104, t0.Q105, 
    t0.Q106, t0.notes.4, t0.Q107_1, t0.Q107_2, t0.Q107_3, t0.Q107_4, t0.Q107_5, t0.Q107_6, t0.Q107_7, 
    t0.Q107_8, t0.Q107_9, t0.Q107_10, t0.Q107_11, t0.Q107_12, t0.Q107_13, t0.Q108_1, t0.Q108_2, 
    t0.Q108_3, t0.Q108_4, t0.Q108_5, t0.Q108_6, t0.Q108_7, t0.Q108_8, t0.Q108_9, t0.Q108_10, 
    t0.Q108_11, t0.Q108_12, t0.Q108_13, t0.Q108_14, t0.Q108_15, t0.Q108_16, t0.Q108_17, t0.Q108_18, 
    t0.Q108_19, t0.Q108_20, t0.Q108_21, t0.Q109_1, t0.Q109_2, t0.Q109_3, t0.Q109_4, t0.Q109_4_TEXT, 
    t0.notes.5, t0.Q110, t0.Q111_1, t0.Q111_2, t0.Q111_3, t0.Q111_4, t0.Q111_5, t0.Q111_5_TEXT, 
    t0.Q112_1, t0.Q112_2, t0.Q112_3, t0.Q112_4, t0.Q112_5, t0.Q112_6, t0.Q112_6_TEXT, t0.Q113_1, 
    t0.Q113_2, t0.Q113_3, t0.Q113_4, t0.Q113_5, t0.Q113_6, t0.Q113_7, t0.Q113_8, t0.Q113_9, t0.Q113_10, 
    t0.Q113_11, t0.Q113_12, t0.Q113_13, t0.Q113_14, t0.Q113_15, t0.Q113_16, t0.Q113_17, t0.Q114, 
    t0.Q115_1, t0.Q115_2, t0.Q115_3, t0.Q115_4, t0.Q115_5, t0.Q116, t0.Q117, t0.Q117_TEXT, t0.Q118, 
    t0.Q119, t0.Q120, t0.Q121, t0.Q122, t0.Q123, t0.Q124, t0.Q125, t0.Q126, t0.Q127_1, t0.Q127_2, 
    t0.Q127_3, t0.Q127_4, t0.Q127_5, t0.Q127_6, t0.Q127_7, t0.Q127_8, t0.Q127_8_TEXT, t0.Q128, t0.Q129, 
    t0.Q130_1, t0.Q130_2, t0.Q130_3, t0.Q130_4, t0.Q130_5, t0.Q130_6, t0.Q130_7, t0.Q130_8, 
    t0.Q130_8_TEXT, t0.Q131, t0.Q132, t0.Q132_TEXT, t0.Q133, t0.Q134, t0.Q135, t0.Q136_1, 
    t0.Q136_1_TEXT, t0.Q136_4, t0.Q136_4_TEXT, t0.Q137, t0.Q138, t0.Q139, t0.Q140, t0.Q141, t0.Q142, 
    t0.Q143, t0.Q144, t0.Q145, t0.Q145_TEXT, t0.Q146, t0.Q147, t0.Q148, t0.Q149, t0.Q150, t0.Q150.0, 
    t0.Q151, t0.Q153, t0.notes.6, t0.Q153.0, t0.Q154, t0.Q154_TEXT, t0.Q156, t0.Q156.0, t0.Q157, 
    t0.Q158, t0.Q159, t0.Q160, t0.Q161, t0.Q162, t0.Q162_TEXT, t0.Q163, t0.Q163_TEXT, t0.Q164, 
    t0.Q164_TEXT, t0.Q165, t0.Q165_TEXT, t0.Q166, t0.Q166_TEXT, t0.Q167, t0.Q168, t0.Q168_TEXT, 
    t0.Q169, t0.Q170, t0.Q170_TEXT, t0.Q171, t0.Q172, t0.Q172_TEXT, t0.Q173, t0.Q173_TEXT, 
    t0.recflood1, t0.recflood2, t0.notes.7, t0.Q174, t0.Q175, t0.Q175_TEXT, t0.Q177, t0.Q177_TEXT, 
    t0.Q178, t0.Q178.0, t0.Q178_TEXT, t0.Q179, t0.Q179_TEXT, t0.Q180, t0.Q181, t0.Q182, t0.Q183, 
    t0.Q184, t0.Q184_TEXT, t0.Q185, t0.Q185_TEXT, t0.Q186, t0.Q186_TEXT, t0.Q187, t0.Q188, t0.Q189, 
    t0.Q190, t0.Q191, t0.Q191_TEXT, t0.Q192, t0.Q193, t0.Q194, t0.Q195, t0.Q196, t0.Q197, t0.Q198, 
    t0.Q199, t0.Q200, t0.Q201_1, t0.Q201_1_TEXT, t0.Q201_2, t0.Q201_2_TEXT, t0.Q202, t0.Q203, t0.Q204, 
    t0.notes.8, t0.Thank_you, t0.LocationLatitude, t0.LocationLongitude, t0.LocationAccuracy, 
    t0.diasterselffeffsumT3, t0.disasterMHsumT3, t0.disasterfatsumT3‎, t0.diasterattribT3, 
    t0.traumaExposureT3, t0.PTSDsumT3, t0.depressionsumT3, t0.anxsumT3, t0.idiomsDistressT3, 
    t0.copingsumT3, t0.socialcohT3, t0.religT3, t0.HelpSeekingT3, t0.helpseekmentalT3, 
    t0.helpseekdisastT3, t0.helpgivingdisterT3, t0.helpgivingmentalT3, 
    t0.HelpSeekingGivingRecentDisasterT3, t0.disasterprepsumT3, t0.floodexp, t0.chronstressT3, 
    t0.traumaexpT3, t0.diasterprepsumT3, t0.functManT3, t0.functWomanT3, t0.functavgT3, 
    t0.womenFunctT3, t0.manFunctT3, t0.functassessT3
  /FROM 'DataSet2' AS t0
  /JOIN * AS t1
    ON t0.T1ParticipantID=t1.T1ParticipantID
  /OUTFILE FILE=*.

DATASET ACTIVATE DataSet3.
COMPUTE functassessavgT3=mean(functmenavgT3, T2functwomenavgT3).
EXECUTE.
